---
# tasks file for linux-mkfs
  - shell: lsblk
    register: lsblk

  - debug:
    msg: "lsblk: {{ lsblk }}"

  - name: "Creating {{item.filesystem_type}} from {{ item.device }}"
    filesystem:
      fstype: "{{ item.filesystem_type }}"
      dev: "{{ item.device }}"
    with_items: "{{ mkfs }}"
    when: mkfs is defined and item.mount_point is defined

  - name: "Checking {{ item.mount_point }}"
    file: 
      path: "{{ item.mount_point }}"
      state: directory
    with_items: "{{ mkfs }}"
    when: mkfs is defined and item.mount_point is defined

  - name: "Mounting {{ item.device }} to {{ item.mount_point }}"
    mount:
      name: "{{ item.mount_point }}"
      src: "{{ item.device }}"
      fstype: "{{ item.filesystem_type }}"
      opts: "{{ item.mount_options }}"
      state: mounted
    with_items: "{{ mkfs }}"
    when: mkfs is defined and item.mount_point is defined